//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.24 at 11:03:23 AM EEST
//

package com.comptel.bst.tools.diff.parser.entity.jaxb.method;

import javax.xml.bind.annotation.XmlRegistry;

import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBOutputParameters;
import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBParameter;
import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBParameterGroup;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.comptel.bst.tools.mergetool.objects.schema.method package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.comptel.bst.tools.mergetool.objects.schema.method
     * 
     */
    public ObjectFactory() {}

    /**
     * Create an instance of {@link JAXBMethodBody }
     * 
     */
    public JAXBMethodBody createBody() {
        return new JAXBMethodBody();
    }

    /**
     * Create an instance of {@link JAXBExec }
     * 
     */
    public JAXBExec createExec() {
        return new JAXBExec();
    }

    public JAXBParameterGroup createInput() {
        return new JAXBParameterGroup();
    }

    /**
     * Create an instance of {@link JAXBInstanceDescription }
     * 
     */
    public JAXBInstanceDescription createInstanceDescription() {
        return new JAXBInstanceDescription();
    }

    /**
     * Create an instance of {@link JAXBJump }
     * 
     */
    public JAXBJump createJump() {
        return new JAXBJump();
    }

    /**
     * Create an instance of {@link JAXBMethod }
     * 
     */
    public JAXBMethod createMethod() {
        return new JAXBMethod();
    }

    /**
     * Create an instance of {@link JAXBNodeOutputParameter }
     * 
     */
    public JAXBNodeOutputParameter createOutParameter() {
        return new JAXBNodeOutputParameter();
    }

    public JAXBOutputParameters createOutput() {
        return new JAXBOutputParameters();
    }

    public JAXBParameter createParameter() {
        return new JAXBParameter();
    }

}
