//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.24 at 11:01:12 AM EEST
//

package com.comptel.bst.tools.diff.parser.entity.jaxb.step;

import javax.xml.bind.annotation.XmlRegistry;

import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBOutputParameters;
import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBParameter;
import com.comptel.bst.tools.diff.parser.entity.jaxb.JAXBParameterGroup;


/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.comptel.bst.tools.mergetool.objects.schema.step package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.comptel.bst.tools.mergetool.objects.schema.step
     * 
     */
    public ObjectFactory() {}

    /**
     * Create an instance of {@link Input }
     * 
     */
    public JAXBParameterGroup createInput() {
        return new JAXBParameterGroup();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public JAXBOutputParameters createOutput() {
        return new JAXBOutputParameters();
    }

    public JAXBParameter createParameter() {
        return new JAXBParameter();
    }

    /**
     * Create an instance of {@link JAXBStep }
     * 
     */
    public JAXBStep createStep() {
        return new JAXBStep();
    }

}
